### ISSUE TITLE
Helm chart incompatible with K8s version >= 1.16

### ISSUE THREAD

**Issue by aktur** [semi-technologies/weaviate-helm#13]
I was following the documentation and get stuck on:
# Deploy
$ helm upgrade \
  --values ./values.yaml \
  --install \
  --namespace "weaviate" \
  "weaviate" \
  weaviate.tgz

Here is what I get:
$ helm upgrade   --values ./values.yaml   --install   --namespace "weaviate"   "weaviate"   weaviate.tgz
Release "weaviate" does not exist. Installing it now.
Error: unable to build kubernetes objects from release manifest: [unable to recognize "": no matches for kind "Deployment" in version "apps/v1beta1", unable to recognize "": no matches for kind "StatefulSet" in version "apps/v1beta1", unable to recognize "": no matches for kind "StatefulSet" in version "apps/v1beta2"]

My setup:
$ helm version
version.BuildInfo{Version:"v3.0.1", GitCommit:"7c22ef9ce89e0ebeb7125ba2ebf7d421f3e82ffa", GitTreeState:"clean", GoVersion:"go1.13.4"}
$ kubectl -n kube-system get pods
NAME                               READY   STATUS    RESTARTS   AGE
coredns-6955765f44-9vx7p           1/1     Running   0          2d17h
coredns-6955765f44-g67tv           1/1     Running   0          2d17h
etcd-minikube                      1/1     Running   0          2d17h
kube-addon-manager-minikube        1/1     Running   0          2d17h
kube-apiserver-minikube            1/1     Running   0          2d17h
kube-controller-manager-minikube   1/1     Running   0          2d17h
kube-proxy-mfdkp                   1/1     Running   0          2d17h
kube-scheduler-minikube            1/1     Running   1          2d17h
storage-provisioner                1/1     Running   0          2d17h

**Comment by etiennedi** [comment]
Thanks for opening this issue. It looks like the resources `Deployment` and `StatefulSet` were moved to different API groups. Can you let us know which Kubernetes version you were using?

**Comment by aktur** [comment]
I use minikube on MacOS Catalina v10.15.1

$ minikube version
minikube version: v1.6.1
commit: 42a9df4854dcea40ec187b6b8f9a910c6038f81a

**Comment by etiennedi** [comment]
Thanks for your reply. Which Kubernetes version is your minikube starting? You can run `kubectl version` after starting the cluster and it will print both client and server version.

**Comment by etiennedi** [comment]
@aktur I found the place in the Kubernetes changelog where this breaks: https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG-1.16.md#deprecations-and-removals

It breaks in 1.16, so if you spin up a Kubernetes cluster of 1.15 or older it should work. I'll look into upgrading our helm chart later. There are two things we need to address:

* Would this change break our existing clusters? I'm aware of use case running K8s 1.12 and 1.13
* Are all the subcharts that we have little influence over compatible with this change?

If both comes up OK, I can release a new version which will be compatible with 1.16 and 1.17

**Comment by aktur** [comment]
Indeed I have a version v1.17.0. So should I downgrade or patiently wait for you?

**Comment by etiennedi** [comment]
Assuming you spun up the minikube cluster to try out weaviate, I'd recommend to tear it down and spin up a new one using `1.15`. You don't need to downgrade minikube itself, you can simply run `minikube start --kubernetes-version 1.15.0`

> or patiently wait for you?

Wouldn't recommend this option, as I don't know how simple or big of a change it will be, therefore also can't give a reliable ETA. :)

**Comment by aktur** [comment]
OK, I'm trying to run it with 1.15.0, got another error:
$ helm upgrade   --values ./values.yaml   --install   --namespace "weaviate"   "weaviate"   weaviate.tgz
Release "weaviate" does not exist. Installing it now.
Error: create: failed to create: namespaces "weaviate" not found

**Comment by etiennedi** [comment]
I think the [docs](https://www.semi.technology/documentation/weaviate/current/installation.html#kubernetes) are missing a step, which is creating the namespace. I'll create an issue for the website/docs.

The helm command tries to install weaviate into a namespace called `weaviate`, but it doesn't seem to exist. You can create the namespace by running

```
kubectl create namespace weaviate
```

beforehand.

However, your release might now be in an odd state, as the chart was installed, but not successful, so to clean up I'd recommend the following order now:

1. Remove the installation by running `helm del --purge weaviate`
2. Create the namepsace using `kubectl create namespace weaviate`
3. Try installing again.

**Comment by aktur** [comment]
Thx so far. I was able to get deployed weaviate, now waiting to get it running.
$ kubectl -n weaviate get pods
NAME                             READY   STATUS              RESTARTS   AGE
contextionary-76c6886b44-t7k4h   0/1     ContainerCreating   0          10m
esvector-master-0                0/1     Pending             0          10m
esvector-master-1                0/1     Pending             0          10m
esvector-master-2                0/1     Pending             0          10m
etcd-0                           0/1     ContainerCreating   0          10m
weaviate-7d7449b658-p8jr4        0/1     Running             4          10m

**Comment by etiennedi** [comment]
To see why a pod is stuck in pending state you can run `kubectl describe <pod name>`, more infos [here](https://kubernetes.io/docs/reference/kubectl/cheatsheet/#viewing-finding-resources).

My guess would be that your cluster doesn't have enough resources for the default values. Please keep in mind, the default `weaviate-helm` setup is meant for a small to medium sized production case. To run with a very small cluster, you can additionally specify the [values-minimal.yaml](https://github.com/semi-technologies/weaviate-helm/blob/master/weaviate/values-minimal.yaml). To do so, when running the helm install/upgrade command append this after the original `values.yaml` like so `--values values.yaml --values values-minimal.yaml`.

Alternatively you can create your own `vaules.yaml` and set the resource requirements exactly so that they fit with your cluster: [Helm Docs - Value Files](https://helm.sh/docs/topics/chart_template_guide/values_files/).

If you are looking at a much easier "just trying to run Weaviate" experience, I'd recommend the [Docker Compose Setup](https://www.semi.technology/documentation/weaviate/current/installation.html#docker-compose) which is designed to quickly spin up the stack in a temporary and ephemeral environment.

**Comment by aktur** [comment]
Hi Etienne,

The docker compose setup does not work for me as it doesn’t preserve data. I’ve already discussed it with Laura and got answer from your that Kubernetes is way to go.

I’ve managed to get the Weaviate run on my minikube setup. Tweaked some settings and imported the getting-started data. It almost work, as after hibernating my laptop and waking it up the schema is still there. However, I can’t do graphql anymore. I’m getting an error that the lock cannot be obtained:

'{"query":"{Get{Things{City{name uuid}}}}"}'
{"data":{"Get":{"Things":{"City":null}}},"errors":[{"locations":[{"column":13,"line":1}],"message":"could not acquire lock: could not get connector lock: etcdserver: requested lease not found","path":["Get","Things","City"]}]}

Any pointers how to fix it?

Summarising of what I want to achieve, have a local weaviate instance to be able play with it even when I’m offline. Docker does not preserve data, minikube has the above mentioned problem.

Kind regards,
Michal

P.S. This is probably no helm problem anymore. I’m glad to move this discussion to other, more appropriate place.

**Comment by etiennedi** [comment]
The default GKE version is now 1.16, so we should address this on priority
