### ISSUE TITLE
CrashLoopBackOff etcd-0 kubernetes docker for windows

### ISSUE THREAD

**Issue by MauRiEEZZZ** [semi-technologies/weaviate-helm#15]
I discovering your product and I tried to deploy weaviate on my locak kubernetes cluster that comes with Docker for windows.

The deployment using helm was succesfully.

> D:\repos\weaviate\weaviate-helm\weaviate>helm install --values .\values-minimal.yaml --namespace "weaviate" "weaviate" weaviate-8.2.1.tgz
NAME: weaviate
LAST DEPLOYED: Tue Jan 21 08:45:25 2020
NAMESPACE: weaviate
STATUS: deployed
REVISION: 1
 
>D:\repos\weaviate\weaviate-helm\weaviate>kubectl get deployment --namespace weaviate
NAME            READY   UP-TO-DATE   AVAILABLE   AGE
contextionary   1/1     1            1           21s
weaviate        0/1     1            0           21s

 But etcd-0 seems to have a hard time.
>D:\repos\weaviate\weaviate-helm\weaviate>kubectl get pods --namespace weaviate
NAME                            READY   STATUS             RESTARTS   AGE
contextionary-fd94d5bb4-vt9tp   1/1     Running            0          39s
esvector-master-0               0/1     Running            1          39s
etcd-0                          0/1     CrashLoopBackOff   2          39s
weaviate-7d5b6fb5c4-pkrqb       0/1     Running            0          39s

The log contains: 
>==> Creating data dir...
mkdir: cannot create directory '/bitnami/etcd/data': Permission denied

**Comment by MauRiEEZZZ** [comment]
additional information:
Docker version 19.03.5, build 633a0ea

kubectl version
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.8", GitCommit:"211047e9a1922595eaa3a1127ed365e9299a6c23", GitTreeState:"clean", BuildDate:"2019-10-15T12:11:03Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.8", GitCommit:"211047e9a1922595eaa3a1127ed365e9299a6c23", GitTreeState:"clean", BuildDate:"2019-10-15T12:02:12Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"linux/amd64"}
 
 helm version
version.BuildInfo{Version:"v3.0.2", GitCommit:"19e47ee3283ae98139d98460de796c1be1e3975f", GitTreeState:"clean", GoVersion:"go1.13.5"}

**Comment by etiennedi** [comment]
Thanks for the detailed output. The versions look good at first first. We haven't evaluated Helm v3 as opposed to Helm v2 yet, but if the Helm chart installation was successful that's probably not the issue.

Since you are seeing
> mkdir: cannot create directory '/bitnami/etcd/data': Permission denied

I assume it's a permission issue with the attached volumes. Could you append the output of `kubectl get pv --namespace weaviate` and `kubectl get pvc --namespace weaviate`? Maybe that'll tell us a bit more about mouting modes/write permissions. Thanks.

**Comment by MauRiEEZZZ** [comment]
Thank you for your superfast response,
>D:\repos\weaviate\weaviate-helm\weaviate>kubectl get pv --namespace weaviate
NAME                                       CAPACITY   ACCESS MODES   RECLAIM POLICY   STATUS   CLAIM                                        STORAGECLASS   REASON   AGE
pvc-daf2be5d-3c3d-11ea-bade-00155d017108   8Gi        RWO            Delete           Bound    weaviate/data-etcd-0                         hostpath                108s
pvc-db2889a8-3c3d-11ea-bade-00155d017108   150Gi      RWO            Delete           Bound    weaviate/esvector-master-esvector-master-0   hostpath                108s
 
>D:\repos\weaviate\weaviate-helm\weaviate>kubectl get pvc --namespace weaviate
NAME                                STATUS   VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS   AGE
data-etcd-0                         Bound    pvc-daf2be5d-3c3d-11ea-bade-00155d017108   8Gi        RWO            hostpath       2m55s
esvector-master-esvector-master-0   Bound    pvc-db2889a8-3c3d-11ea-bade-00155d017108   150Gi      RWO            hostpath       2m55s

**Comment by etiennedi** [comment]
Closing, as I assume this has been resolved. But since `etcd` is also no longer part of the Weaviate stack, the issue itself is most likely obsolete.
