### ISSUE TITLE
Scaling weaviate and contextionary not in values

### ISSUE THREAD

**Issue by fefi42** [semi-technologies/weaviate-helm#22]
It is only manually possible to scale both the weaviate and the contextionary helm chart manually.

While the values has a value for the weaviate replicas this value is never used: https://github.com/semi-technologies/weaviate-helm/blob/master/weaviate/values.yaml#L16

The value for the contextionary is completely missing.

Not that scaling the weaviate pod might lead to issues when changing the schema: https://github.com/semi-technologies/weaviate/issues/725

**Comment by etiennedi** [comment]
Thanks for noticing. If you have some time/capacity to fix this, I'd be happy to accept a PR.

**Comment by fefi42** [comment]
That you shall have https://github.com/semi-technologies/weaviate-helm/pull/23
